name: Build and push

permissions:
  contents: read

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/ssh-key-authority

on:
  push:
    branches: [ "master", "dev" ]
    paths-ignore:
      - README.md
      - docs/**
      - "**/*.md"
      - ".gitignore"
  pull_request:
    branches: [ "master", "dev" ]
    paths-ignore:
      - README.md
      - docs/**
      - "**/*.md"
      - ".gitignore"
  release:
    types: [ published ]

jobs:
  build:
    if: github.event_name != 'release'
    runs-on: ubuntu-latest
    steps:
    - &checkout-step
      name: Check out repository
      uses: actions/checkout@v4

    - &setup-qemu-step
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - &login-step
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - &setup-buildx-step
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: |
          ${{ env.IMAGE_NAME }}:latest-${{ github.ref_name }}

  release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
    - *checkout-step

    - *setup-qemu-step

    - *login-step

    - *setup-buildx-step

    - name: Build and push release image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        tags: |
          ${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}
          ${{ env.IMAGE_NAME }}:latest
